name:                sudoku
version:             0.1.0.0
github:              "alistairc/sudoku"
license:             BSD3
author:              "Alistair Cooke"
maintainer:          "alistair.cooke77@gmail.com"
copyright:           "(c) Alistair Cooke"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alistairc/sudoku#readme>

default-extensions:
  #This is the GHC2021 set, but that option's not in LTS stackage yet
  - BangPatterns
  - BinaryLiterals
  - ConstrainedClassMethods
  - ConstraintKinds
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyCase
  - EmptyDataDecls
  - EmptyDataDeriving
  - ExistentialQuantification
  - ExplicitForAll
  # - FieldSelectors # not in our version of ghc
  - FlexibleContexts
  - FlexibleInstances
  - ForeignFunctionInterface
  - GADTSyntax
  - GeneralisedNewtypeDeriving
  - HexFloatLiterals
  - ImplicitPrelude
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - MonomorphismRestriction
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NamedWildCards
  - NumericUnderscores
  - PatternGuards
  - PolyKinds
  - PostfixOperators
  - RankNTypes
  - RelaxedPolyRec
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - StarIsType
  - TraditionalRecordSyntax
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeSynonymInstances


dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - split
  - mtl
  - haskeline

executables:
  sudoku-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudoku
    - haskeline
    - mtl

tests:
  sudoku-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudoku
    - hspec
    - mtl
